services:
  - type: web
    name: mindbridge-school
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        value: admin123
    
databases:
  - name: mindbridge-db
    databaseName: mindbridge_school
    user: mindbridge_user

